# build stage
FROM node:22-slim AS build-stage
ENV NODE_OPTIONS=--openssl-legacy-provider
WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY . /app/
RUN npm run build

# production stage
FROM alpine:3.12 as production-stage
RUN mkdir -p /vue
COPY --from=build-stage /app/dist /vue

CMD ["tail", "-f", "/dev/null"]