# build stage
FROM node:13.6.0 as build-stage
WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY . /app/
RUN npm run build

# production stage
FROM alpine:3.9 as production-stage
RUN mkdir -p /vue
COPY --from=build-stage /app/dist /vue

CMD ["tail", "-f", "/dev/null"]