# build stage
FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY . /app/
RUN npm run build

# production stage
FROM alpine:3.9 as production-stage
RUN mkdir -p /vue
COPY --from=build-stage /app/dist /vue

# RUN chown -R "$USER":www-data /usr/share/nginx/html
# RUN chmod -R 755 /usr/share/nginx/html

CMD ["tail", "-f", "/dev/null"]