site_name: pkdb
site_description: Pharmacokinetics of experimental data. 
repo_url: https://github.com/pkdb
site_dir: site
copyright: Copyright &copy; 2018
dev_addr: 0.0.0.0:8001

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
