"""Definition of database users and roles."""

DEFAULT_PASSWORD = "pkdb"

USERS_DATA = [
    {
        "username": "janekg",
        "first_name": "Jan",
        "last_name": "Grzegorzewski",
        "email": "janekg89@hotmail.de",
        "groups": ["admin"],
    },
    {
        "username": "mkoenig",
        "first_name": "Matthias",
        "last_name": "König",
        "email": "koenigmx@hu-berlin.de",
        "groups": ["admin"],
    },
    {
        "username": "dimitra",
        "first_name": "Dimitra",
        "last_name": "Eleftheriadou",
        "email": "dim.ele.paok@gmail.com",
        "groups": ["basic"],
    },
    {
        "username": "kgreen",
        "first_name": "Kathleen",
        "last_name": "Green",
        "email": "test@test.com",
        "groups": ["basic"],
    },
    {
        "username": "jbrandhorst",
        "first_name": "Janosch",
        "last_name": "Brandhorst",
        "email": "jbrandhorst1@googlemail.com",
        "groups": ["basic"],
    },
    {
        "username": "FlorBar",
        "first_name": "Florian",
        "last_name": "Bartsch",
        "email": "bartsflo@hu-berlin.de",
        "groups": ["basic"],
    },
    {
        "username": "deepa",
        "first_name": "Deepa",
        "last_name": "Maheshvare",
        "email": "deepamahm.iisc@gmail.com",
        "groups": ["basic"],
    },
    {
        "username": "yduport",
        "first_name": "Yannick",
        "last_name": "Duport",
        "email": "yannid86@zedat.fu-berlin.de",
        "groups": ["basic"],
    },
    {
        "username": "adriankl",
        "first_name": "Adrian",
        "last_name": "Koeller",
        "email": "adriankl39@googlemail.com",
        "groups": ["basic"],
    },
    {
        "username": "dannythekey",
        "first_name": "Danny",
        "last_name": "Ke",
        "email": "danny.yujia.ke@gmail.com",
        "groups": ["basic"],
    },
    {
        "username": "SaraD-hub",
        "first_name": "Sara",
        "last_name": "De Angelis",
        "email": "deangelis.sara@icould.com",
        "groups": ["basic"],
    },
    {
        "username": "balcisue",
        "first_name": "Sükrü",
        "last_name": "Balci",
        "email": "skbalci@gmail.com",
        "groups": ["basic"],
    },
    {
        "username": "paula-ogata",
        "first_name": "Paul",
        "last_name": "Ogata",
        "email": "up201900135@fe.up.pt",
        "groups": ["basic"],
    },
    {
        "username": "lepujolh",
        "first_name": "Helen",
        "last_name": "Leal",
        "email": "helenl_29@hotmail.de",
        "groups": ["basic"],
    },
    {
        "username": "stemllb",
        "first_name": "Beatrice",
        "last_name": "Stemmer Mallol",
        "email": "stemallb@hu-berlin.de",
        "groups": ["basic"],
    },
    {
        "username": "jonaspk98",
        "first_name": "Jonas",
        "last_name": "Küttner",
        "email": "jonas.kuettner98@gmail.com",
        "groups": ["basic"],
    },
    {
        "username": "reviewer",
        "first_name": "reviewer",
        "last_name": "test",
        "email": "reviewer@googlemail.com",
        "groups": ["reviewer"],
    },
    {
        "username": "xresearch",
        "first_name": "XResearch",
        "last_name": "Group",
        "email": "koenigmx@hu-berlin.de",
        "groups": ["basic"],
    },
    {
        "username": "Ahmed-fub",
        "first_name": "Ahmed",
        "last_name": "Atta",
        "email": "Ahmed-fub@xresearch.de",
        "groups": ["basic"],
    },
    {
        "username": "DaryaChb",
        "first_name": "Darya",
        "last_name": "Chobat",
        "email": "DaryaChb@xresearch.de",
        "groups": ["basic"],
    },
    {
        "username": "DaryaLigay",
        "first_name": "Darya",
        "last_name": "Ligay",
        "email": "DaryaLigay@xresearch.de",
        "groups": ["basic"],
    },
    {
        "username": "drosdekv",
        "first_name": "Vanessa",
        "last_name": "Drosdek",
        "email": "drosdekv@xresearch.de",
        "groups": ["basic"],
    },
    {
        "username": "long231a",
        "first_name": "Lucia",
        "last_name": "Link",
        "email": "long231a@xresearch.de",
        "groups": ["basic"],
    },
    {
        "username": "lucialink30",
        "first_name": "Lucia",
        "last_name": "Link",
        "email": "lucialink30@xresearch.de",
        "groups": ["basic"],
    },
    {
        "username": "Mattimatti1",
        "first_name": "Mathis",
        "last_name": "Hertel",
        "email": "Mattimatti1@xresearch.de",
        "groups": ["basic"],
    },
    {
        "username": "Ming-Yuen",
        "first_name": "Ng",
        "last_name": "Ming",
        "email": "Ming@xresearch.de",
        "groups": ["basic"],
    },
    {
        "username": "MuellTim",
        "first_name": "Tim",
        "last_name": "Mueller",
        "email": "MuellTim@xresearch.de",
        "groups": ["basic"],
    },
    {
        "username": "sarahdv7",
        "first_name": "Sarah",
        "last_name": "Davoudzadeh",
        "email": "sarahdv7@xresearch.de",
        "groups": ["basic"],
    },
    {
        "username": "shihabmo",
        "first_name": "Mohammad",
        "last_name": "Shihab",
        "email": "shihabmo@xresearch.de",
        "groups": ["basic"],
    },
    {
        "username": "SophieSilberhorn",
        "first_name": "Sophie",
        "last_name": "Silberhorn",
        "email": "SophieSilberhorn@xresearch.de",
        "groups": ["basic"],
    },
    {
        "username": "wumbor",
        "first_name": "Victor",
        "last_name": "Kumbol",
        "email": "wumbor@xresearch.de",
        "groups": ["basic"],
    },
    {
        "username": "DariusSchulze",
        "first_name": "Darius",
        "last_name": "Schulze",
        "email": "DariusSchulze@xresearch.de",
        "groups": ["basic"],
    },
    {
        "username": "fuokibedi",
        "first_name": "Frances",
        "last_name": "Okibedi",
        "email": "franceo88@zedat.fu-berlin.de",
        "groups": ["basic"],
    },
    {
        "username": "Soji4eva",
        "first_name": "Narudeem",
        "last_name": "Sojimade",
        "email": "Soji4eva@gmail.com",
        "groups": ["basic"],
    },
    {
        "username": "amdangelica",
        "first_name": "Amanda",
        "last_name": "Lim",
        "email": "a.lim@campus.tu-berlin.de",
        "groups": ["basic"],
    },
    {
        "username": "dzinty",
        "first_name": "Kseniia",
        "last_name": "Petukhova",
        "email": "xenia.nice@gmail.com",
        "groups": ["basic"],
    },
    {
        "username": "Rain-marine",
        "first_name": "Bahri",
        "last_name": "Zahra",
        "email": "bahri.zahra79@gmail.com",
        "groups": ["basic"],
    },
    {
        "username": "linafrolova",
        "first_name": "Lina",
        "last_name": "Frolova",
        "email": "xenianice@gmail.com",
        "groups": ["basic"],
    },
    {
        "username": "gozdemkarapinar",
        "first_name": "Gozdem",
        "last_name": "Karapinar",
        "email": "gozdemkarapinar@gmail.com",
        "groups": ["basic"],
    },
    {
        "username": "jonathanspeh",
        "first_name": "Michel Jonathan",
        "last_name": "Speh",
        "email": "michel-jonathan.speh@charite.de",
        "groups": ["basic"],
    },
    {
        "username": "Raj-codes",
        "first_name": "Raj Prateek",
        "last_name": "Rai",
        "email": "raiprate@student.hu-berlin.de",
        "groups": ["basic"],
    },
    {
        "username": "MadNietzsche",
        "first_name": "Antonio",
        "last_name": "Alvarez",
        "email": "antonio.alvarez@student.hu-berlin.de",
        "groups": ["basic"],
    },
    {
        "username": "lisapolzer",
        "first_name": "Lisa",
        "last_name": "Polzer",
        "email": "lisa.polzer@fu-berlin.de",
        "groups": ["basic"],
    },
    {
        "username": "FrancaLe",
        "first_name": "Franca",
        "last_name": "Lemor",
        "email": "franca.lemor@gmail.com",
        "groups": ["basic"],
    },
    {
        "username": "hannah3menghis",
        "first_name": "Hannah",
        "last_name": "Menghis",
        "email": "hannah_menghis@brown.edu",
        "groups": ["basic"],
    },
    {
        "username": "SamLuca",
        "first_name": "Luca Samuel",
        "last_name": "Sawady",
        "email": "luca.sawady@fu-berlin.de",
        "groups": ["basic"],
    },
    {
        "username": "shubhankarpalwankar",
        "first_name": "Shubhankar",
        "last_name": "Palwankar",
        "email": "shubhankarpalwankar6@gmail.com",
        "groups": ["basic"],
    },
    {
        "username": "DeepaMahm",
        "first_name": "Deepa",
        "last_name": "Maheshvare",
        "email": "deepamahm.iisc@gmail.com",
        "groups": ["basic"],
    },
    {
        "username": "MariiaMysh",
        "first_name": "Mariia",
        "last_name": "Myshkina",
        "email": "myshkina.mariia@gmail.com",
        "groups": ["basic"],
    },
    {
        "username": "rohinichakraborty",
        "first_name": "Rohini",
        "last_name": "Chakraborty",
        "email": "rohinichakraborty0217@gmail.com",
        "groups": ["basic"],
    },
    {
        "username": "nikenemitz",
        "first_name": "Nike",
        "last_name": "Nemitz",
        "email": "nike.philine.elise@gmail.com",
        "groups": ["basic"],
    },
    {
        "username": "ykulanoglu",
        "first_name": "Yusuf Ali",
        "last_name": "Kulanoglu",
        "email": "yusufalikul55@gmail.com",
        "groups": ["basic"],
    },
    {
        "username": "tereshchuk1",
        "first_name": "Vera",
        "last_name": "Tereshchuk",
        "email": "pikilla2017@gmail.com",
        "groups": ["basic"],
    },
    {
        "username": "ennietensil",
        "first_name": "Ennie",
        "last_name": "Tensil",
        "email": "ennie@tensil.de",
        "groups": ["basic"],
    },
    {
        "username": "jen-ne-sse",
        "first_name": "Jennesse",
        "last_name": "Alejandro",
        "email": "jennesse_alejandro@brown.edu",
        "groups": ["basic"],
    },
    {
        "username": "mii-halina",
        "first_name": "Michelle",
        "last_name": "Elias",
        "email": "michelleelias66@gmail.com",
        "groups": ["basic"],
    },
    {
        "username": "bibymaths",
        "first_name": "Abhinav",
        "last_name": "Mishra",
        "email": "mishraabhinav36@gmail.com",
        "groups": ["basic"],
    },
    {
        "username": "elisabettacasabianca11",
        "first_name": "Elisabetta",
        "last_name": "Casabianca",
        "email": "elisabetta.casabianca.11@gmail.com",
        "groups": ["basic"],
    },
    {
        "username": "icalledmyselfmoon",
        "first_name": "Mariia",
        "last_name": "Babaeva",
        "email": "icalledmyselfmoon@gmail.com",
        "groups": ["basic"],
    },
    {
        "username": "unfulw",
        "first_name": "Kim",
        "last_name": "Minjun",
        "email": "kim.minjun@u.nus.edu",
        "groups": ["basic"],
    },
    {
        "username": "bellatgy",
        "first_name": "Isabella",
        "last_name": "Tan",
        "email": "bella.tan@mail.utoronto.ca",
        "groups": ["basic"],
    },
    {
        "username": "oliviaayau",
        "first_name": "Olivia",
        "last_name": "Yau",
        "email": "oliviaayau@gmail.com",
        "groups": ["basic"],
    },
    {
        "username": "Juan-hub129",
        "first_name": "Juan Pablo",
        "last_name": "Ramos Mendoza",
        "email": "juan.rmendoza@alumnos.udg.mx",
        "groups": ["basic"],
    },
    {
        "username": "monajes",
        "first_name": "Monika",
        "last_name": "Jesionek",
        "email": "monika.jesionek@student.uj.edu.pl",
        "groups": ["basic"],
    },
    {
        "username": "jzhannes",
        "first_name": "Johannes",
        "last_name": "Metternich",
        "email": "metternich@campus.tu-berlin.de",
        "groups": ["basic"],
    },
    {
        "username": "changlinh",
        "first_name": "Linh",
        "last_name": "Chang",
        "email": "changlin@student.hu-berlin.de",
        "groups": ["basic"],
    },
    {
        "username": "Shelee97",
        "first_name": "Shelee",
        "last_name": "Badon",
        "email": "sheleepab97@zedat.fu-berlin.de",
        "groups": ["basic"],
    },
    {
        "username": "jessicalienx97-wq",
        "first_name": "Jessica",
        "last_name": "Cruz",
        "email": "jessicalien.x97@gmail.com",
        "groups": ["basic"],
    },
    {
        "username": "sandeep-konakagautamdas",
        "first_name": "Sandeep Konaka",
        "last_name": "Gautamdas",
        "email": "sandeepkonaka.g@gmail.com",
        "groups": ["basic"],
    },
]

USER_GROUPS_DATA = [
    {"name": "basic"},
    {"name": "reviewer"},
    {"name": "admin"},
]
