# Generated by Django 2.0.6 on 2018-08-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interventions', '0001_initial'),
        ('comments', '0001_initial'),
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, related_name='comments', to='studies.Reference'),
        ),
        migrations.AddField(
            model_name='comment',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, related_name='comments', to='studies.Study'),
        ),
        migrations.AddField(
            model_name='comment',
            name='timecourse',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, related_name='comments', to='interventions.Timecourse'),
        ),
    ]
