"""Scientific measurement policies used when compiling vocabulary definitions."""

TIME_REQUIRED_MEASUREMENT_TYPES = [
    "concentration",
    "cumulative amount",
    "metabolic ratio",
    "cumulative metabolic ratio",
    "recovery",
    "auc_end",
    "ptf",
]

CAN_NEGATIVE = [
    "tmax",
    # Absolute and relative changes (including derived change measurements)
    # can describe decreases from baseline.
    "pH change",
    "concentration change",
    "concentration change absolute",
    "cumulative amount (change)",
    "blood pressure systolic (change)",
    "blood pressure systolic (change relative)",
    "blood pressure systolic auc_end (change)",
    "blood pressure diastolic (change)",
    "blood pressure diastolic (change relative)",
    "blood pressure diastolic auc_end (change)",
    "MAP (change absolute)",
    "MAP (change relative)",
    "systemic vascular resistance (change relative)",
    "renin activity (change absolute)",
    "renin activity (change relative)",
    "heart rate (change)",
    "heart rate (change relative)",
    "EHR change",
    "EHR change AUEC",
    "EHR change average",
    "EHR change fluctuations",
    "weight (change)",
    "weight (change relative)",
    "hba1c (change)",
    "inr (change)",
    "prothrombin time (change)",
    "prothrombin time (change relative)",
    "prothrombin time (change relative) maximum",
    "modified prothrombin time (change)",
    "mPT (change relative)",
    "aPTT (change)",
    "aPTT (change relative)",
    "ETP (change relative)",
    "HepTest (change relative)",
    "thrombin activity (change relative)",
    "antithrombin activity (change relative)",
    "urinary volume (change)",
]
