// Functional browser regression tests against the bundled app with an isolated API fixture.
import { chromium } from '../../frontend/node_modules/playwright/index.mjs';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const root = new URL('../../python/src/pkdb/curation/static/', import.meta.url);
const state = { csrf_token:'fixture-csrf',workspace:'/tmp/curation-fixture',endpoint:'https://example.invalid',account:'curator',offline:false,paused:false,vocabulary:{status:'current'},github:{user:'github-curator',users:[{login:'github-curator',name:'Example Curator'},{login:'second',name:'Second User'}],issues:[{number:1,title:'drug/Example2026',html_url:'https://github.com/example/data/issues/1',assignees:['github-curator'],study_ids:['one']},{number:2,title:'NotLocal2026',html_url:'https://github.com/example/data/issues/2',assignees:['github-curator'],study_ids:[]}]},studies:[{id:'one',name:'Example2026',sid:'PKDB00001',path:'drug/Example2026',status:'invalid',mode:'validate',files:[{id:'outputs.xlsx',path:'outputs.xlsx'}],problems:[{severity:'error',code:'vocabulary.unknown',message:'Unknown measurement <script>alert(1)</script>',source:{file:'outputs.xlsx',sheet:'Sheet1',cell:'C10'},suggestions:[{message:'Choose a supported measurement.'}]}]},{id:'two',name:'Second2026',sid:'PKDB00002',path:'drug/Second2026',status:'discovered',mode:'validate',files:[],problems:[]}],jobs:[]};
state.jobs = [{id:'queued-job',study_id:'two',action:'validate',status:'queued'}, {id:'unknown-job',study_id:'one',action:'upload',status:'unknown',persistence:'unknown',endpoint:'https://example.invalid'}];
const calls = [], errors = [];
const browser = await chromium.launch({headless:true});
try {
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  page.on('pageerror',error=>errors.push(error.message));
  await page.route('http://curation.test/**',async route=>{
    const req=route.request(), path=new URL(req.url()).pathname;
    if (path.startsWith('/local/')) {
      if(req.method()==='POST') {const body=req.postDataJSON();calls.push({path,body,csrf:req.headers()['x-csrf-token']});if(path==='/local/settings')Object.assign(state.github,{user:body.github_user || state.github.user});if(path==='/local/pause')state.paused=body.paused;}
      await route.fulfill({contentType:'application/json',body:JSON.stringify(path==='/local/state'?state:{csrf_token:'fixture-csrf'})});return;
    }
    const file=path==='/'?'index.html':path.replace('/static/','');
    await route.fulfill({contentType:file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.png')?'image/png':'text/html',body:await readFile(new URL(file,root))});
  });
  await page.goto('http://curation.test/#token=fixture-launch');
  await page.getByRole('button',{name:'Example2026',exact:true}).waitFor();
  assert.equal(new URL(page.url()).hash,'');
  assert.equal(await page.locator('main .workspace-controls, main .connection-card').count(), 0);
  assert((await page.locator('.study-overview').boundingBox()).y < 150);
  await page.locator('summary').filter({hasText:'Workspace'}).click();
  assert(await page.locator('header #workspace-open').isVisible());
  await page.keyboard.press('Escape');
  await page.locator('summary').filter({hasText:'File watching'}).click();
  await page.locator('#pause').click();
  await page.waitForFunction(()=>document.querySelector('#watch-indicator').textContent === 'Paused');
  await page.keyboard.press('Escape');
  await page.locator('#studies tr').first().locator('td').nth(2).click();
  assert.match(await page.locator('.problem').textContent(), /C10/);
  assert.equal(await page.locator('#selection-count').textContent(), '0 studies selected');
  await page.getByRole('button', {name:'Overview', exact:true}).click();
  await page.locator('#studies tr').first().locator('td').nth(3).click();
  assert.match(await page.locator('.problem').textContent(), /C10/);
  const logo = page.locator('header img[alt="PK-DB"]');
  await logo.waitFor();
  assert.equal(await page.locator('#study-detail img').count(), 0);
  assert((await logo.boundingBox()).width <= 50);
  await page.waitForFunction(() => { const img = document.querySelector('header img'); return img.complete && img.naturalWidth > 0; });
  await page.locator('#studies tr').nth(1).focus();
  await page.keyboard.press('Enter');
  assert.match(await page.locator('#study-detail').textContent(), /No diagnostics available/);
  await page.locator('#studies tr').first().focus();
  await page.keyboard.press('Space');
  assert.match(await page.locator('.problem').textContent(), /C10/);
  await page.getByRole('checkbox',{name:'Select Example2026',exact:true}).check();
  assert.match(await page.locator('.problem').textContent(), /C10/);
  await page.getByRole('button',{name:'Validate now',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('queued'));
  assert(calls.some(c=>c.path==='/local/jobs'&&c.body.action==='validate'&&c.body.ids[0]==='one'&&c.csrf==='fixture-csrf'));
  await page.getByRole('button',{name:'Example2026',exact:true}).click();
  assert.equal(await page.locator('#github-user').count(), 0);
  assert.equal(await page.locator('#user-search').count(), 0);
  const overview = await page.locator('.study-overview').boundingBox();
  const detail = await page.locator('#study-detail').boundingBox();
  assert(detail.x > overview.x + overview.width);
  assert.match(await page.locator('.problem').textContent(), /C10/);
  assert.match(await page.locator('.problem').textContent(),/C10/);
  assert.match(await page.locator('.problem').textContent(),/<script>alert/);
  assert.match(await page.locator('.problem').textContent(),/Choose a supported measurement/);
  await page.locator('#study-detail').getByRole('button',{name:'Validate',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('queued'));
  await page.getByRole('button',{name:'Open file',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('default application'));
  assert(calls.some(c=>c.path==='/local/files/open'&&c.body.file==='outputs.xlsx'));
  await page.getByRole('button',{name:'Upload selected',exact:true}).click();
  assert.match(await page.locator('#upload-context').textContent(),/example.invalid.*curator/);
  assert(!calls.some(c=>c.path==='/local/jobs'&&c.body.action==='upload'));
  await page.locator('#upload-dialog').getByRole('button',{name:'Validate and upload',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('upload job'));
  assert(calls.some(c=>c.path==='/local/jobs'&&c.body.action==='upload'));
  await page.locator('#study-search').fill('does-not-exist');
  assert.equal(await page.locator('#selection-count').textContent(),'0 studies selected');
  await page.locator('summary').filter({hasText:'Connection'}).click();
  assert(await page.locator('header #endpoint').isVisible());
  assert(await page.locator('header #vocabulary').isVisible());
  await page.getByRole('button',{name:'Connection settings',exact:true}).click();
  await page.locator('#settings-key').fill('fake-browser-key');
  await page.locator('#settings-dialog').getByRole('button',{name:'Cancel',exact:true}).click();
  assert.equal(await page.locator('#settings-key').inputValue(),'');
  await page.getByRole('button',{name:'Cancel queued job',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('Queued job canceled'));
  assert(calls.some(c=>c.path==='/local/jobs/cancel'&&c.body.ids[0]==='queued-job'));
  await page.getByRole('button',{name:'Clear finished history',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('Finished history cleared'));
  assert(calls.some(c=>c.path==='/local/history/clear'));
  await page.getByRole('button',{name:'Review unknown outcome',exact:true}).click();
  assert(!calls.some(c=>c.path==='/local/retry'));
  assert.match(await page.locator('#retry-context').textContent(),/Previous target: https:\/\/example.invalid/);
  await page.locator('#retry-acknowledge').check();
  await page.getByRole('button',{name:'Validate and retry upload',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('Explicit retry queued'));
  assert(calls.some(c=>c.path==='/local/retry'&&c.body.id==='one'&&c.body.acknowledge_unknown===true));
  assert((await page.locator('.problem').boundingBox()).height < 130);
  await page.locator('#study-search').fill('');
  assert((await page.locator('#studies tr').first().boundingBox()).height < 60);
  await page.setViewportSize({width:390,height:844});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  const mobileOverview = await page.locator('.study-overview').boundingBox();
  const mobileDetail = await page.locator('#study-detail').boundingBox();
  assert(mobileDetail.y >= mobileOverview.y + mobileOverview.height);
  await page.screenshot({path:'/tmp/curation-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.locator('#study-search').fill('');
  await page.screenshot({path:'/tmp/curation-desktop.png',fullPage:true});
  assert.deepEqual(errors,[]);
  console.log('Curation browser smoke passed: session, validation, diagnostics, safe rendering, file opening, upload review, automatic problems, selection, credential clearing, cancellation, history, explicit retry, responsive layout.');
} finally {await browser.close();}
