# Generated by Django 2.0.6 on 2018-06-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(blank=True, to='studies.Author'),
        ),
    ]
