# Generated by Django 2.0.6 on 2018-06-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_auto_20180619_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='sid',
        ),
        migrations.AddField(
            model_name='study',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='authors', to='studies.Author'),
        ),
        migrations.AlterField(
            model_name='study',
            name='title',
            field=models.TextField(),
        ),
    ]
