# Generated by Django 2.1.5 on 2019-02-04 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('interventions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('groupset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='subjects.GroupSet')),
                ('individualset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='subjects.IndividualSet')),
                ('interventionset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='interventions.InterventionSet')),
                ('outputset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='interventions.OutputSet')),
            ],
        ),
    ]
