# Generated by Django 2.1.5 on 2019-01-25 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interventions', '0001_initial'),
        ('subjects', '0001_initial'),
        ('studies', '0001_initial'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='studies.Study'),
        ),
        migrations.AddField(
            model_name='comment',
            name='characteristica_ex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='subjects.CharacteristicaEx'),
        ),
        migrations.AddField(
            model_name='comment',
            name='group_ex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='subjects.GroupEx'),
        ),
        migrations.AddField(
            model_name='comment',
            name='groupset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='subjects.GroupSet'),
        ),
        migrations.AddField(
            model_name='comment',
            name='individual_ex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='subjects.IndividualEx'),
        ),
        migrations.AddField(
            model_name='comment',
            name='individualset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='subjects.IndividualSet'),
        ),
        migrations.AddField(
            model_name='comment',
            name='intervention_ex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='interventions.InterventionEx'),
        ),
        migrations.AddField(
            model_name='comment',
            name='interventionset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='interventions.InterventionSet'),
        ),
        migrations.AddField(
            model_name='comment',
            name='output_ex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='interventions.OutputEx'),
        ),
        migrations.AddField(
            model_name='comment',
            name='outputset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='interventions.OutputSet'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='studies.Reference'),
        ),
        migrations.AddField(
            model_name='comment',
            name='study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='studies.Study'),
        ),
        migrations.AddField(
            model_name='comment',
            name='timecourse_ex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='interventions.TimecourseEx'),
        ),
    ]
