from pathlib import Path

from pkdb.studyformat.export import column_reference, json_schemas
from pkdb.studyformat.tables import TABLES

DOCS = Path(__file__).resolve().parents[3] / "docs" / "study-format.md"


def test_schema_files():
    schemas = json_schemas()
    assert sorted(schemas) == sorted(
        ["study.schema.json", "review.schema.json"]
        + [f"{kind}.row.schema.json" for kind in TABLES]
    )
    assert "format" in schemas["study.schema.json"]["properties"]
    assert "items" in schemas["review.schema.json"]["properties"]


def test_row_schema_mirrors_the_table():
    schema = json_schemas()["outputs.row.schema.json"]
    assert list(schema["properties"]) == list(TABLES["outputs"].names)
    assert schema["x-pkdb-columns"] == list(TABLES["outputs"].names)
    assert schema["x-pkdb-file"] == "outputs_<source>.tsv"
    assert sorted(schema["required"]) == ["measurement", "subjects"]
    assert schema["properties"]["error_type"]["enum"] == ["sd", "se", "gsd"]
    assert schema["properties"]["mean"]["examples"] == [2.9]
    time = schema["properties"]["time"]
    assert {"type": "number"} in time["anyOf"] and {
        "const": "NR",
        "type": "string",
    } in time["anyOf"]
    assert schema["properties"]["interventions"]["anyOf"][0]["type"] == "array"


def test_column_reference_lists_every_column():
    text = column_reference()
    assert text.startswith("<!-- Generated by `pkdb schema docs`")
    for spec in TABLES.values():
        for column in spec.columns:
            assert f"| `{column.name}` |" in text
    assert chr(0x2014) not in text


def test_committed_column_reference_is_current():
    assert DOCS.read_text(encoding="utf-8") == column_reference()
