# Generated by Django 3.0.7 on 2020-06-16 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outputs', '0001_initial'),
        ('subjects', '0001_initial'),
        ('studies', '0001_initial'),
        ('data', '0002_dimension_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='studies.Study'),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='outputs',
            field=models.ManyToManyField(through='data.Dimension', to='outputs.Output'),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='subset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='data.SubSet'),
        ),
        migrations.AddField(
            model_name='data',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='data.DataSet'),
        ),
        migrations.AddField(
            model_name='data',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='subjects.DataFile'),
        ),
    ]
