"""support verified email and account throttling

Revision ID: 24471de5f5a4
Revises: 7dd23f32b5f9
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "24471de5f5a4"
down_revision: str | Sequence[str] | None = "7dd23f32b5f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_throttles",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_account_throttles")),
    )
    op.create_index(
        op.f("ix_account_throttles_expires_at"),
        "account_throttles",
        ["expires_at"],
        unique=False,
    )
    op.create_table(
        "email_addresses",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_email_addresses_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_addresses")),
        sa.UniqueConstraint("email", name=op.f("uq_email_addresses_email")),
    )
    op.create_index(
        op.f("ix_email_addresses_user_id"), "email_addresses", ["user_id"], unique=False
    )
    op.add_column("tokens", sa.Column("email_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_tokens_email_id_email_addresses"),
        "tokens",
        "email_addresses",
        ["email_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "users", sa.Column("first_name", sa.String(), nullable=False, server_default="")
    )
    op.add_column(
        "users", sa.Column("last_name", sa.String(), nullable=False, server_default="")
    )
    op.add_column(
        "users",
        sa.Column(
            "pending_verification",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "pending_verification")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_constraint(
        op.f("fk_tokens_email_id_email_addresses"), "tokens", type_="foreignkey"
    )
    op.drop_column("tokens", "email_id")
    op.drop_index(op.f("ix_email_addresses_user_id"), table_name="email_addresses")
    op.drop_table("email_addresses")
    op.drop_index(
        op.f("ix_account_throttles_expires_at"), table_name="account_throttles"
    )
    op.drop_table("account_throttles")
    # ### end Alembic commands ###
