# Generated by Django 3.0.6 on 2020-06-10 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('figures', '0001_initial'),
        ('subjects', '0001_initial'),
        ('outputs', '0001_initial'),
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='subjects.DataFile'),
        ),
        migrations.AddField(
            model_name='figure',
            name='outputset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='outputs.OutputSet'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='dataset_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='figures.DataSetPoint'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='outputs.Output'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='studies.Study'),
        ),
        migrations.AddField(
            model_name='datasetpoint',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_points', to='figures.DataSet'),
        ),
        migrations.AddField(
            model_name='datasetpoint',
            name='outputs',
            field=models.ManyToManyField(through='figures.Dimension', to='outputs.Output'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='figure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='figures.Figure'),
        ),
    ]
