# Generated by Django 2.1.5 on 2019-02-04 12:01

from django.db import migrations, models
import pkdb_app.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('glycolysis', 'glycolysis'), ('gluconeogenesis', 'gluconeogenesis'), ('oxidative phosphorylation', 'oxidative phosphorylation'), ('hypoglycemia', 'hypoglycemia'), ('insulin secretion', 'insulin secretion'), ('diabetes', 'diabetes'), ('oral glucose tolerance test', 'oral glucose tolerance test'), ('intravenous glucose tolerance test', 'intravenous glucose tolerance test')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('pmid', models.CharField(max_length=200, null=True)),
                ('sid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('doi', models.CharField(max_length=150, null=True)),
                ('title', models.TextField()),
                ('abstract', models.TextField(null=True)),
                ('journal', models.TextField(null=True)),
                ('date', models.DateField()),
                ('pdf', models.FileField(null=True, storage=pkdb_app.storage.OverwriteStorage(), upload_to='study')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('sid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('pkdb_version', models.IntegerField(default=[1.0])),
                ('name', models.CharField(max_length=200)),
                ('design', models.CharField(choices=[('single group', 'single group'), ('parallel group', 'parallel group'), ('crossover', 'crossover'), ('cohort', 'cohort'), ('case control', 'case control')], max_length=200, null=True)),
                ('licence', models.CharField(choices=[('open', 'open'), ('close', 'close')], max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'studies',
            },
        ),
    ]
