# Generated by Django 2.1.5 on 2019-01-25 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interventions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studies', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_studies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='study',
            name='curators',
            field=models.ManyToManyField(related_name='curator_of_studies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='study',
            name='files',
            field=models.ManyToManyField(to='subjects.DataFile'),
        ),
        migrations.AddField(
            model_name='study',
            name='groupset',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study', to='subjects.GroupSet'),
        ),
        migrations.AddField(
            model_name='study',
            name='individualset',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study', to='subjects.IndividualSet'),
        ),
        migrations.AddField(
            model_name='study',
            name='interventionset',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study', to='interventions.InterventionSet'),
        ),
        migrations.AddField(
            model_name='study',
            name='keywords',
            field=models.ManyToManyField(related_name='studies', to='studies.Keyword'),
        ),
        migrations.AddField(
            model_name='study',
            name='outputset',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study', to='interventions.OutputSet'),
        ),
        migrations.AddField(
            model_name='study',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=True, related_name='study', to='studies.Reference'),
        ),
        migrations.AddField(
            model_name='study',
            name='substances',
            field=models.ManyToManyField(related_name='studies', to='interventions.Substance'),
        ),
        migrations.AddField(
            model_name='reference',
            name='authors',
            field=models.ManyToManyField(related_name='references', to='studies.Author'),
        ),
    ]
