"""JSON Schema and the Markdown column reference, derived from the table declarations."""

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, create_model

from pkdb.studyformat.cells import parse_cell
from pkdb.studyformat.columns import Column, ColumnType
from pkdb.studyformat.models import Review, StudyMetadata
from pkdb.studyformat.tables import TABLES, TableSpec, table_file

T = ColumnType
_TYPES: dict[ColumnType, Any] = {
    T.TEXT: str,
    T.NAME: str,
    T.NAMES: list[str],
    T.NUMBER: float,
    T.INTEGER: Annotated[int, Field(ge=0)],
    T.TIME: float,
    T.TIMES: list[float],
    T.UNIT: str,
    T.TERM: str,
    T.ENUM: str,
    T.SOURCE: str,
}
_LABELS: dict[ColumnType, tuple[str, ...]] = {
    T.TEXT: ("text",),
    T.NAME: ("name",),
    T.NAMES: ("comma-separated names",),
    T.NUMBER: ("number",),
    T.INTEGER: ("whole number",),
    T.TIME: ("number",),
    T.TIMES: ("number", "`;`-separated numbers"),
    T.UNIT: ("unit",),
    T.TERM: ("vocabulary term",),
    T.ENUM: ("choice",),
    T.SOURCE: ("source",),
}


def _file(spec: TableSpec) -> str:
    return table_file(spec.kind, "<source>" if spec.per_source else None)


def _annotation(column: Column) -> Any:
    # Choices sit inside the string branch so that an optional column stays nullable.
    annotation = (
        Literal.__getitem__(column.choices) if column.choices else _TYPES[column.type]
    )
    return annotation | Literal["NR"] if column.allows_nr else annotation


def _example(column: Column) -> list[Any] | None:
    if not column.example:
        return None
    value, _ = parse_cell(column, column.example)
    return [list(value) if isinstance(value, tuple) else value]


def row_model(spec: TableSpec) -> type[BaseModel]:
    """Pydantic model of one table row; columns that are not required are optional."""
    fields: dict[str, Any] = {}
    for column in spec.columns:
        options: dict[str, Any] = {
            "description": column.description,
            "examples": _example(column),
        }
        if column.name in spec.required_columns:
            fields[column.name] = (_annotation(column), Field(**options))
        else:
            fields[column.name] = (
                _annotation(column) | None,
                Field(default=None, **options),
            )
    return create_model(
        f"{spec.kind.capitalize()}Row",
        __config__=ConfigDict(extra="forbid", title=f"Row of {_file(spec)}"),
        **fields,
    )


def json_schemas() -> dict[str, dict]:
    """JSON Schemas by file name for `study.json`, `review.json` and table rows."""
    schemas = {
        "study.schema.json": StudyMetadata.model_json_schema(),
        "review.schema.json": Review.model_json_schema(),
    }
    for spec in TABLES.values():
        schema = row_model(spec).model_json_schema()
        schema["description"] = (
            f"{spec.description} Each line of the TSV file is one row; an empty cell is null. "
            "Values are the parsed cells: comma-separated names and `;`-separated times are arrays."
        )
        schema["x-pkdb-file"] = _file(spec)
        schema["x-pkdb-columns"] = list(spec.names)
        schemas[f"{spec.kind}.row.schema.json"] = schema
    return schemas


def type_label(column: Column) -> str:
    """Description of the values a column accepts, as shown in the column reference."""
    if column.vocabulary:
        alternatives = [f"vocabulary: {column.vocabulary.replace('_', ' ')}"]
    elif column.choices:
        alternatives = [
            "one of " + ", ".join(f"`{choice}`" for choice in column.choices)
        ]
    else:
        alternatives = list(_LABELS[column.type])
    if column.allows_nr:
        alternatives.append("`NR`")
    if len(alternatives) == 1:
        return alternatives[0]
    return f"{', '.join(alternatives[:-1])} or {alternatives[-1]}"


def _required(spec: TableSpec, column: Column) -> str:
    if column.owned:
        return "no, written by `pkdb format`"
    return "yes" if column.name in spec.required_columns else "no"


def column_reference() -> str:
    """Markdown column reference of all tables, as written by `pkdb schema docs`."""
    lines = [
        "<!-- Generated by `pkdb schema docs` from python/src/pkdb/studyformat. Do not edit this file. -->",
        "",
        "# Study format",
        "",
        '!!! note "Study format 2 is being introduced"',
        "",
        "    This page describes study format 2. The studies in pkdb_data are still in study format 1 until the migration; `pkdb format`, `pkdb validate`, `pkdb prepare` and `pkdb upload` all support study format 2 folders.",
        "",
        "A study folder in study format 2 contains `study.json`, `reference.json`, `review.json`, the tab-separated tables below, the publication PDF and an image `<study>_<source>.png` for every paper table or figure the data come from. `pkdb format` writes all files in canonical form, `pkdb validate` checks them, `pkdb tables` edits the tables in a [workbook](workbooks.md), and `pkdb schema export` writes the same definitions as JSON Schema.",
        "",
        "## Identity and upload",
        "",
        "A study is identified by its folder location `<substance>/<name>`, for example `caffeine/Harder1988`: the folder name is the study name and its parent folder the substance. The folder names `publication` and `validate` are reserved, because PK-DB uses them in study URLs. `pkdb upload` sends the exact text of `study.json` and `reference.json` and every other file of the folder to `/api/v2/studies/<substance>/<name>`, where the server validates the folder like `pkdb validate` and stores the study. The study page is `/data/<substance>/<name>`.",
        "",
        "A released study has a PKDB identifier in the `release` block of `study.json`. Uploading a folder with a `release.pkdb_id` takes over the study that PK-DB stores under that identifier and renames it to the folder location, so a moved or renamed folder keeps its study. A folder without one, or whose PKDB identifier no stored study has, takes over the study format 1 study of the same publication and source, if you may edit it. PKDB identifiers and former study format 1 identifiers in URLs, such as `/data/PKDB00198` or `/data/Vilsboll2008`, redirect to the study.",
        "",
        "## Statistics and schedules",
        "",
        "There is no `value` column. `mean` is the arithmetic mean, the value of a single subject (count 1) or, with the calculation `unspecified summary`, the central value of a summary whose statistic the publication does not state. `cv` and `gcv` are entered in percent and are fractions in the prepared study and the API. A digitized `error_bar` with its `error_type` completes `sd`, `se` or `gsd`; missing `sd`, `se` and `cv` are derived from each other, and `gsd` and `gcv` as well, where the reported values allow it, and reported statistics that contradict each other, including an error bar, are a warning that a review item acknowledges at the column of the statistic that disagrees with the most others (see the [data model](data-model.md)). An intervention `time` is a number, or a `;`-separated list for an irregular schedule; a regular schedule uses `interval` and `doses` instead.",
        "",
        "## Review",
        "",
        "`review.json` holds the review status (`draft`, `in_review`, `approved`), the reviewers and the review items. `approved_by` and `approved` record the person who approved the study and when; `pkdb review status <study> approved` requires zero open items and zero validation errors and is refused for agents (`--agent` or `PKDB_AGENT`). A dismissed item no longer acknowledges a warning. `pkdb study` and `pkdb review` write `study.json` and `review.json`; every write is refused when the file changed since the revision the caller read.",
        "",
        "## Tables",
        "",
        "| File | Content | Required |",
        "|---|---|---|",
    ]
    for spec in TABLES.values():
        lines.append(
            f"| `{_file(spec)}` | {spec.description} | {'yes' if spec.required else 'no'} |"
        )
    lines += [
        "",
        "## Raw extraction",
        "",
        "Every paper table and figure can keep its raw extraction beside the rows mapped into the tables. `<study>_<source>.tsv` is a paper table as printed: a grid of text cells in their printed positions without a header line, `study` or `source` columns. `pkdb format` strips the cells, pads the rows to the widest row and removes trailing empty cells and empty rows, and never sorts the rows or parses numbers. In the workbook it is the sheet `<study>_<source>` after the data sheets, written as text cells; `pkdb tables add <study> --raw Tab2` adds it.",
        "",
        "`<study>_<source>.wpd.json` is a WebPlotDigitizer 4 project digitized on the figure image `<study>_<source>.png`, imported with `pkdb digitize import <study> <source> <file>` from a `wpd.json` or a saved `.tar` project. Only XY axes are supported. A dataset named like a timecourse `label` holds the central values of that series (time on x; `mean`, else `median`, else `gmean` on y), a dataset `<label>;error_bar` the ends of its error bars, and a dataset named like a scatter `name` its points. Digitize and map in the units printed on the axes. `pkdb validate` warns about datasets without rows (`unknown_dataset`) and rows more than 2 pixels from their dataset (`digitized_mismatch`), and `pkdb plot` draws both on the image.",
        "",
        "## TSV encoding",
        "",
        "- UTF-8 without byte order mark, LF line endings and a final newline.",
        "- Tab separated without quoting. Cells contain no tabs or line breaks.",
        "- One header row with every template column in template order.",
        "- An empty cell means missing. `NR` (not reported) is allowed only in `time` and `time_unit` and their scatter variants `x_time`, `x_time_unit`, `y_time` and `y_time_unit`.",
        "- Numbers use a decimal point and are written in their shortest form.",
        "- `pkdb format` sorts the rows and writes the `study` column and, in files named after a source, the `source` column.",
    ]
    for spec in TABLES.values():
        lines += [
            "",
            f"## `{_file(spec)}`",
            "",
            spec.description,
            "",
            "| Column | Type | Required | Description |",
            "|---|---|---|---|",
        ]
        lines += [
            f"| `{column.name}` | {type_label(column)} | {_required(spec, column)} | {column.description} |"
            for column in spec.columns
        ]
    return "\n".join(lines) + "\n"
