"""initial relational schema

Revision ID: 4fc4c2157761
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "4fc4c2157761"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "references",
        sa.Column("sid", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("pmid", sa.String(), nullable=True),
        sa.Column("doi", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("abstract", sa.String(), nullable=True),
        sa.Column("journal", sa.String(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_references")),
        sa.UniqueConstraint("sid", name=op.f("uq_references_sid")),
    )
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('admin', 'curator', 'reviewer', 'user')",
            name=op.f("ck_users_role"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "vocabulary_nodes",
        sa.Column("sid", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column(
            "definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("mass", sa.Float(), nullable=True),
        sa.Column("formula", sa.String(), nullable=True),
        sa.Column("charge", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "mass IS NULL OR mass > 0", name=op.f("ck_vocabulary_nodes_positive_mass")
        ),
        sa.PrimaryKeyConstraint("sid", name=op.f("pk_vocabulary_nodes")),
    )
    op.create_index(
        op.f("ix_vocabulary_nodes_kind"), "vocabulary_nodes", ["kind"], unique=False
    )
    op.create_index(
        op.f("ix_vocabulary_nodes_name"), "vocabulary_nodes", ["name"], unique=False
    )
    op.create_table(
        "vocabulary_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.CheckConstraint("id = 1", name=op.f("ck_vocabulary_version_singleton")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vocabulary_version")),
    )
    op.create_table(
        "files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("original_name", sa.String(), nullable=False),
        sa.Column("ready", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("size >= 0", name=op.f("ck_files_size")),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_files_owner_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_files")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_files_storage_key")),
    )
    op.create_index(op.f("ix_files_expires_at"), "files", ["expires_at"], unique=False)
    op.create_index(op.f("ix_files_owner_id"), "files", ["owner_id"], unique=False)
    op.create_table(
        "reference_authors",
        sa.Column("reference_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.CheckConstraint("position >= 0", name=op.f("ck_reference_authors_position")),
        sa.ForeignKeyConstraint(
            ["reference_id"],
            ["references.id"],
            name=op.f("fk_reference_authors_reference_id_references"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "reference_id", "position", name=op.f("pk_reference_authors")
        ),
    )
    op.create_table(
        "studies",
        sa.Column("sid", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("access", sa.String(length=16), nullable=False),
        sa.Column("licence", sa.String(length=16), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column("reference_id", sa.Integer(), nullable=True),
        sa.Column("source_digest", sa.String(length=64), nullable=True),
        sa.Column("vocabulary_version", sa.String(), nullable=True),
        sa.Column("processing_version", sa.String(), nullable=True),
        sa.Column(
            "validation_report", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "source_manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "access IN ('public', 'private')", name=op.f("ck_studies_access")
        ),
        sa.CheckConstraint(
            "licence IN ('open', 'closed')", name=op.f("ck_studies_licence")
        ),
        sa.CheckConstraint("length(sid) > 0", name=op.f("ck_studies_sid")),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["users.id"], name=op.f("fk_studies_creator_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["reference_id"],
            ["references.id"],
            name=op.f("fk_studies_reference_id_references"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_studies")),
        sa.UniqueConstraint("reference_id", name=op.f("uq_studies_reference_id")),
        sa.UniqueConstraint("sid", name=op.f("uq_studies_sid")),
    )
    op.create_index(
        op.f("ix_studies_creator_id"), "studies", ["creator_id"], unique=False
    )
    op.create_index(op.f("ix_studies_name"), "studies", ["name"], unique=False)
    op.create_table(
        "tokens",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tokens")),
        sa.UniqueConstraint("digest", name=op.f("uq_tokens_digest")),
    )
    op.create_index(op.f("ix_tokens_user_id"), "tokens", ["user_id"], unique=False)
    op.create_table(
        "vocabulary_edges",
        sa.Column("child", sa.String(length=255), nullable=False),
        sa.Column("parent", sa.String(length=255), nullable=False),
        sa.CheckConstraint(
            "child <> parent", name=op.f("ck_vocabulary_edges_not_self")
        ),
        sa.ForeignKeyConstraint(
            ["child"],
            ["vocabulary_nodes.sid"],
            name=op.f("fk_vocabulary_edges_child_vocabulary_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent"],
            ["vocabulary_nodes.sid"],
            name=op.f("fk_vocabulary_edges_parent_vocabulary_nodes"),
        ),
        sa.PrimaryKeyConstraint("child", "parent", name=op.f("pk_vocabulary_edges")),
    )
    op.create_table(
        "vocabulary_terms",
        sa.Column("node_sid", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_sid"],
            ["vocabulary_nodes.sid"],
            name=op.f("fk_vocabulary_terms_node_sid_vocabulary_nodes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "node_sid", "kind", "value", name=op.f("pk_vocabulary_terms")
        ),
    )
    op.create_table(
        "groups",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=512), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint("count >= 0", name=op.f("ck_groups_count")),
        sa.CheckConstraint(
            "parent_id IS NULL OR parent_id <> id", name=op.f("ck_groups_not_self")
        ),
        sa.ForeignKeyConstraint(
            ["study_id", "parent_id"],
            ["groups.study_id", "groups.id"],
            name=op.f("fk_groups_study_id_parent_id_groups"),
            initially="IMMEDIATE",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["studies.id"],
            name=op.f("fk_groups_study_id_studies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_groups")),
        sa.UniqueConstraint("study_id", "id", name=op.f("uq_groups_study_id_id")),
        sa.UniqueConstraint("study_id", "key", name=op.f("uq_groups_study_id_key")),
        sa.UniqueConstraint("study_id", "name", name=op.f("uq_groups_study_id_name")),
    )
    op.create_index(op.f("ix_groups_parent_id"), "groups", ["parent_id"], unique=False)
    op.create_index(op.f("ix_groups_study_id"), "groups", ["study_id"], unique=False)
    op.create_table(
        "interventions",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("time", sa.Float(), nullable=True),
        sa.Column("time_text", sa.String(), nullable=True),
        sa.Column("time_end", sa.Float(), nullable=True),
        sa.Column("time_unit", sa.String(), nullable=True),
        sa.Column("route", sa.String(length=255), nullable=True),
        sa.Column("application", sa.String(length=255), nullable=True),
        sa.Column("form", sa.String(length=255), nullable=True),
        sa.Column("derived_from_id", sa.Integer(), nullable=True),
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=512), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("measurement_type", sa.String(length=255), nullable=False),
        sa.Column("substance", sa.String(length=255), nullable=True),
        sa.Column("calculation_type", sa.String(length=255), nullable=True),
        sa.Column("choice", sa.String(), nullable=True),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("mean", sa.Float(), nullable=True),
        sa.Column("median", sa.Float(), nullable=True),
        sa.Column("minimum", sa.Float(), nullable=True),
        sa.Column("maximum", sa.Float(), nullable=True),
        sa.Column("sd", sa.Float(), nullable=True),
        sa.Column("se", sa.Float(), nullable=True),
        sa.Column("cv", sa.Float(), nullable=True),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("source", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "origin IN ('reported', 'normalized', 'calculated')",
            name=op.f("ck_interventions_origin"),
        ),
        sa.CheckConstraint(
            "count IS NULL OR count >= 0", name=op.f("ck_interventions_count")
        ),
        sa.ForeignKeyConstraint(
            ["application"],
            ["vocabulary_nodes.sid"],
            name=op.f("fk_interventions_application_vocabulary_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["calculation_type"],
            ["vocabulary_nodes.sid"],
            name=op.f("fk_interventions_calculation_type_vocabulary_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["form"],
            ["vocabulary_nodes.sid"],
            name=op.f("fk_interventions_form_vocabulary_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["measurement_type"],
            ["vocabulary_nodes.sid"],
            name=op.f("fk_interventions_measurement_type_vocabulary_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["route"],
            ["vocabulary_nodes.sid"],
            name=op.f("fk_interventions_route_vocabulary_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["study_id", "derived_from_id"],
            ["interventions.study_id", "interventions.id"],
            name=op.f("fk_interventions_study_id_derived_from_id_interventions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["studies.id"],
            name=op.f("fk_interventions_study_id_studies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["substance"],
            ["vocabulary_nodes.sid"],
            name=op.f("fk_interventions_substance_vocabulary_nodes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interventions")),
        sa.UniqueConstraint(
            "study_id", "id", name=op.f("uq_interventions_study_id_id")
        ),
        sa.UniqueConstraint(
            "study_id", "key", name=op.f("uq_interventions_study_id_key")
        ),
        sa.UniqueConstraint(
            "study_id",
            "name",
            "origin",
            name=op.f("uq_interventions_study_id_name_origin"),
        ),
    )
    op.create_index(
        op.f("ix_interventions_measurement_type"),
        "interventions",
        ["measurement_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interventions_study_id"), "interventions", ["study_id"], unique=False
    )
    op.create_index(
        op.f("ix_interventions_substance"), "interventions", ["substance"], unique=False
    )
    op.create_table(
        "notes",
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("record_key", sa.String(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["studies.id"],
            name=op.f("fk_notes_study_id_studies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notes_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notes")),
    )
    op.create_index(op.f("ix_notes_study_id"), "notes", ["study_id"], unique=False)
    op.create_table(
        "scatters",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("data_type", sa.String(), nullable=False),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=512), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["studies.id"],
            name=op.f("fk_scatters_study_id_studies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scatters")),
        sa.UniqueConstraint("study_id", "id", name=op.f("uq_scatters_study_id_id")),
        sa.UniqueConstraint("study_id", "key", name=op.f("uq_scatters_study_id_key")),
    )
    op.create_index(
        op.f("ix_scatters_study_id"), "scatters", ["study_id"], unique=False
    )
    op.create_table(
        "study_attachments",
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"], ["files.id"], name=op.f("fk_study_attachments_file_id_files")
        ),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["studies.id"],
            name=op.f("fk_study_attachments_study_id_studies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "study_id", "file_id", name=op.f("pk_study_attachments")
        ),
        sa.UniqueConstraint(
            "study_id", "name", name=op.f("uq_study_attachments_study_id_name")
        ),
    )
    op.create_table(
        "study_users",
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.CheckConstraint(
            "role IN ('curator', 'collaborator')", name=op.f("ck_study_users_role")
        ),
        sa.CheckConstraint(
            "rating IS NULL OR (rating >= 0 AND rating <= 5)",
            name=op.f("ck_study_users_rating"),
        ),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["studies.id"],
            name=op.f("fk_study_users_study_id_studies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_study_users_user_id_users")
        ),
        sa.PrimaryKeyConstraint(
            "study_id", "user_id", "role", name=op.f("pk_study_users")
        ),
    )
    op.create_table(
        "timecourses",
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=512), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["studies.id"],
            name=op.f("fk_timecourses_study_id_studies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_timecourses")),
        sa.UniqueConstraint("study_id", "id", name=op.f("uq_timecourses_study_id_id")),
        sa.UniqueConstraint(
            "study_id", "key", name=op.f("uq_timecourses_study_id_key")
        ),
    )
    op.create_index(
        op.f("ix_timecourses_study_id"), "timecourses", ["study_id"], unique=False
    )
    op.create_table(
        "individuals",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=512), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["study_id", "group_id"],
            ["groups.study_id", "groups.id"],
            name=op.f("fk_individuals_study_id_group_id_groups"),
        ),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["studies.id"],
            name=op.f("fk_individuals_study_id_studies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_individuals")),
        sa.UniqueConstraint("study_id", "id", name=op.f("uq_individuals_study_id_id")),
        sa.UniqueConstraint(
            "study_id", "key", name=op.f("uq_individuals_study_id_key")
        ),
        sa.UniqueConstraint(
            "study_id", "name", name=op.f("uq_individuals_study_id_name")
        ),
    )
    op.create_index(
        op.f("ix_individuals_group_id"), "individuals", ["group_id"], unique=False
    )
    op.create_index(
        op.f("ix_individuals_study_id"), "individuals", ["study_id"], unique=False
    )
    op.create_table(
        "subsets",
        sa.Column("scatter_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=512), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["study_id", "scatter_id"],
            ["scatters.study_id", "scatters.id"],
            name=op.f("fk_subsets_study_id_scatter_id_scatters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["studies.id"],
            name=op.f("fk_subsets_study_id_studies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subsets")),
        sa.UniqueConstraint(
            "scatter_id", "position", name=op.f("uq_subsets_scatter_id_position")
        ),
        sa.UniqueConstraint("study_id", "id", name=op.f("uq_subsets_study_id_id")),
        sa.UniqueConstraint("study_id", "key", name=op.f("uq_subsets_study_id_key")),
    )
    op.create_index(op.f("ix_subsets_study_id"), "subsets", ["study_id"], unique=False)
    op.create_table(
        "characteristics",
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("individual_id", sa.Integer(), nullable=True),
        sa.Column("derived_from_id", sa.Integer(), nullable=True),
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=512), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("measurement_type", sa.String(length=255), nullable=False),
        sa.Column("substance", sa.String(length=255), nullable=True),
        sa.Column("calculation_type", sa.String(length=255), nullable=True),
        sa.Column("choice", sa.String(), nullable=True),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("mean", sa.Float(), nullable=True),
        sa.Column("median", sa.Float(), nullable=True),
        sa.Column("minimum", sa.Float(), nullable=True),
        sa.Column("maximum", sa.Float(), nullable=True),
        sa.Column("sd", sa.Float(), nullable=True),
        sa.Column("se", sa.Float(), nullable=True),
        sa.Column("cv", sa.Float(), nullable=True),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("source", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "origin IN ('reported', 'normalized', 'calculated')",
            name=op.f("ck_characteristics_origin"),
        ),
        sa.CheckConstraint(
            "(group_id IS NULL) <> (individual_id IS NULL)",
            name=op.f("ck_characteristics_one_subject"),
        ),
        sa.CheckConstraint(
            "count IS NULL OR count >= 0", name=op.f("ck_characteristics_count")
        ),
        sa.ForeignKeyConstraint(
            ["calculation_type"],
            ["vocabulary_nodes.sid"],
            name=op.f("fk_characteristics_calculation_type_vocabulary_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["measurement_type"],
            ["vocabulary_nodes.sid"],
            name=op.f("fk_characteristics_measurement_type_vocabulary_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["study_id", "derived_from_id"],
            ["characteristics.study_id", "characteristics.id"],
            name=op.f("fk_characteristics_study_id_derived_from_id_characteristics"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["study_id", "group_id"],
            ["groups.study_id", "groups.id"],
            name=op.f("fk_characteristics_study_id_group_id_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["study_id", "individual_id"],
            ["individuals.study_id", "individuals.id"],
            name=op.f("fk_characteristics_study_id_individual_id_individuals"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["studies.id"],
            name=op.f("fk_characteristics_study_id_studies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["substance"],
            ["vocabulary_nodes.sid"],
            name=op.f("fk_characteristics_substance_vocabulary_nodes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_characteristics")),
        sa.UniqueConstraint(
            "study_id", "id", name=op.f("uq_characteristics_study_id_id")
        ),
        sa.UniqueConstraint(
            "study_id", "key", name=op.f("uq_characteristics_study_id_key")
        ),
    )
    op.create_index(
        op.f("ix_characteristics_measurement_type"),
        "characteristics",
        ["measurement_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_characteristics_study_id"),
        "characteristics",
        ["study_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_characteristics_substance"),
        "characteristics",
        ["substance"],
        unique=False,
    )
    op.create_table(
        "measurements",
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("individual_id", sa.Integer(), nullable=True),
        sa.Column("derived_from_id", sa.Integer(), nullable=True),
        sa.Column("derived_from_course_id", sa.Integer(), nullable=True),
        sa.Column("series_key", sa.String(), nullable=True),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("output_type", sa.String(), nullable=False),
        sa.Column("time", sa.Float(), nullable=True),
        sa.Column("time_unit", sa.String(), nullable=True),
        sa.Column("time_not_reported", sa.Boolean(), nullable=False),
        sa.Column("time_unit_not_reported", sa.Boolean(), nullable=False),
        sa.Column("tissue", sa.String(length=255), nullable=True),
        sa.Column("method", sa.String(length=255), nullable=True),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=512), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("measurement_type", sa.String(length=255), nullable=False),
        sa.Column("substance", sa.String(length=255), nullable=True),
        sa.Column("calculation_type", sa.String(length=255), nullable=True),
        sa.Column("choice", sa.String(), nullable=True),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("mean", sa.Float(), nullable=True),
        sa.Column("median", sa.Float(), nullable=True),
        sa.Column("minimum", sa.Float(), nullable=True),
        sa.Column("maximum", sa.Float(), nullable=True),
        sa.Column("sd", sa.Float(), nullable=True),
        sa.Column("se", sa.Float(), nullable=True),
        sa.Column("cv", sa.Float(), nullable=True),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("source", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "origin IN ('reported', 'normalized', 'calculated')",
            name=op.f("ck_measurements_origin"),
        ),
        sa.CheckConstraint(
            "output_type IN ('output', 'timecourse', 'array')",
            name=op.f("ck_measurements_output_type"),
        ),
        sa.CheckConstraint(
            "(group_id IS NULL) <> (individual_id IS NULL)",
            name=op.f("ck_measurements_one_subject"),
        ),
        sa.CheckConstraint(
            "count IS NULL OR count >= 0", name=op.f("ck_measurements_count")
        ),
        sa.ForeignKeyConstraint(
            ["calculation_type"],
            ["vocabulary_nodes.sid"],
            name=op.f("fk_measurements_calculation_type_vocabulary_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["measurement_type"],
            ["vocabulary_nodes.sid"],
            name=op.f("fk_measurements_measurement_type_vocabulary_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["method"],
            ["vocabulary_nodes.sid"],
            name=op.f("fk_measurements_method_vocabulary_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["study_id", "derived_from_course_id"],
            ["timecourses.study_id", "timecourses.id"],
            name=op.f("fk_measurements_study_id_derived_from_course_id_timecourses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["study_id", "derived_from_id"],
            ["measurements.study_id", "measurements.id"],
            name=op.f("fk_measurements_study_id_derived_from_id_measurements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["study_id", "group_id"],
            ["groups.study_id", "groups.id"],
            name=op.f("fk_measurements_study_id_group_id_groups"),
        ),
        sa.ForeignKeyConstraint(
            ["study_id", "individual_id"],
            ["individuals.study_id", "individuals.id"],
            name=op.f("fk_measurements_study_id_individual_id_individuals"),
        ),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["studies.id"],
            name=op.f("fk_measurements_study_id_studies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["substance"],
            ["vocabulary_nodes.sid"],
            name=op.f("fk_measurements_substance_vocabulary_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["tissue"],
            ["vocabulary_nodes.sid"],
            name=op.f("fk_measurements_tissue_vocabulary_nodes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_measurements")),
        sa.UniqueConstraint("study_id", "id", name=op.f("uq_measurements_study_id_id")),
        sa.UniqueConstraint(
            "study_id", "key", name=op.f("uq_measurements_study_id_key")
        ),
    )
    op.create_index(
        op.f("ix_measurements_group_id"), "measurements", ["group_id"], unique=False
    )
    op.create_index(
        op.f("ix_measurements_individual_id"),
        "measurements",
        ["individual_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_measurements_measurement_type"),
        "measurements",
        ["measurement_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_measurements_study_id"), "measurements", ["study_id"], unique=False
    )
    op.create_index(
        op.f("ix_measurements_substance"), "measurements", ["substance"], unique=False
    )
    op.create_table(
        "measurement_interventions",
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("measurement_id", sa.Integer(), nullable=False),
        sa.Column("intervention_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["study_id", "intervention_id"],
            ["interventions.study_id", "interventions.id"],
            name=op.f(
                "fk_measurement_interventions_study_id_intervention_id_interventions"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["study_id", "measurement_id"],
            ["measurements.study_id", "measurements.id"],
            name=op.f(
                "fk_measurement_interventions_study_id_measurement_id_measurements"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "study_id",
            "measurement_id",
            "intervention_id",
            name=op.f("pk_measurement_interventions"),
        ),
        sa.UniqueConstraint(
            "measurement_id",
            "position",
            name=op.f("uq_measurement_interventions_measurement_id_position"),
        ),
    )
    op.create_table(
        "subset_dimensions",
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("subset_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("dimension", sa.String(), nullable=False),
        sa.Column("measurement_id", sa.Integer(), nullable=False),
        sa.Column("shared", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["study_id", "measurement_id"],
            ["measurements.study_id", "measurements.id"],
            name=op.f("fk_subset_dimensions_study_id_measurement_id_measurements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["study_id", "subset_id"],
            ["subsets.study_id", "subsets.id"],
            name=op.f("fk_subset_dimensions_study_id_subset_id_subsets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "study_id", "subset_id", "position", name=op.f("pk_subset_dimensions")
        ),
    )
    op.create_table(
        "timecourse_points",
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("timecourse_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("measurement_id", sa.Integer(), nullable=False),
        sa.CheckConstraint("position >= 0", name=op.f("ck_timecourse_points_position")),
        sa.ForeignKeyConstraint(
            ["study_id", "measurement_id"],
            ["measurements.study_id", "measurements.id"],
            name=op.f("fk_timecourse_points_study_id_measurement_id_measurements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["study_id", "timecourse_id"],
            ["timecourses.study_id", "timecourses.id"],
            name=op.f("fk_timecourse_points_study_id_timecourse_id_timecourses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "study_id", "timecourse_id", "position", name=op.f("pk_timecourse_points")
        ),
        sa.UniqueConstraint(
            "timecourse_id",
            "measurement_id",
            name=op.f("uq_timecourse_points_timecourse_id_measurement_id"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("timecourse_points")
    op.drop_table("subset_dimensions")
    op.drop_table("measurement_interventions")
    op.drop_index(op.f("ix_measurements_substance"), table_name="measurements")
    op.drop_index(op.f("ix_measurements_study_id"), table_name="measurements")
    op.drop_index(op.f("ix_measurements_measurement_type"), table_name="measurements")
    op.drop_index(op.f("ix_measurements_individual_id"), table_name="measurements")
    op.drop_index(op.f("ix_measurements_group_id"), table_name="measurements")
    op.drop_table("measurements")
    op.drop_index(op.f("ix_characteristics_substance"), table_name="characteristics")
    op.drop_index(op.f("ix_characteristics_study_id"), table_name="characteristics")
    op.drop_index(
        op.f("ix_characteristics_measurement_type"), table_name="characteristics"
    )
    op.drop_table("characteristics")
    op.drop_index(op.f("ix_subsets_study_id"), table_name="subsets")
    op.drop_table("subsets")
    op.drop_index(op.f("ix_individuals_study_id"), table_name="individuals")
    op.drop_index(op.f("ix_individuals_group_id"), table_name="individuals")
    op.drop_table("individuals")
    op.drop_index(op.f("ix_timecourses_study_id"), table_name="timecourses")
    op.drop_table("timecourses")
    op.drop_table("study_users")
    op.drop_table("study_attachments")
    op.drop_index(op.f("ix_scatters_study_id"), table_name="scatters")
    op.drop_table("scatters")
    op.drop_index(op.f("ix_notes_study_id"), table_name="notes")
    op.drop_table("notes")
    op.drop_index(op.f("ix_interventions_substance"), table_name="interventions")
    op.drop_index(op.f("ix_interventions_study_id"), table_name="interventions")
    op.drop_index(op.f("ix_interventions_measurement_type"), table_name="interventions")
    op.drop_table("interventions")
    op.drop_index(op.f("ix_groups_study_id"), table_name="groups")
    op.drop_index(op.f("ix_groups_parent_id"), table_name="groups")
    op.drop_table("groups")
    op.drop_table("vocabulary_terms")
    op.drop_table("vocabulary_edges")
    op.drop_index(op.f("ix_tokens_user_id"), table_name="tokens")
    op.drop_table("tokens")
    op.drop_index(op.f("ix_studies_name"), table_name="studies")
    op.drop_index(op.f("ix_studies_creator_id"), table_name="studies")
    op.drop_table("studies")
    op.drop_table("reference_authors")
    op.drop_index(op.f("ix_files_owner_id"), table_name="files")
    op.drop_index(op.f("ix_files_expires_at"), table_name="files")
    op.drop_table("files")
    op.drop_table("vocabulary_version")
    op.drop_index(op.f("ix_vocabulary_nodes_name"), table_name="vocabulary_nodes")
    op.drop_index(op.f("ix_vocabulary_nodes_kind"), table_name="vocabulary_nodes")
    op.drop_table("vocabulary_nodes")
    op.drop_table("users")
    op.drop_table("references")
    # ### end Alembic commands ###
