"""preserve calculated provenance through normalization

Revision ID: 7dd23f32b5f9
Revises: 30fe14280237
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "7dd23f32b5f9"
down_revision: str | Sequence[str] | None = "30fe14280237"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "characteristics",
        sa.Column(
            "calculated", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column(
        "interventions",
        sa.Column(
            "calculated", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column(
        "measurements",
        sa.Column(
            "calculated", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    # ### end Alembic commands ###

    for table in ("characteristics", "interventions", "measurements"):
        op.execute(
            sa.text(f"UPDATE {table} SET calculated = true WHERE origin = 'calculated'")
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("measurements", "calculated")
    op.drop_column("interventions", "calculated")
    op.drop_column("characteristics", "calculated")
    # ### end Alembic commands ###
