import "vuetify/styles";
import "@fortawesome/fontawesome-free/css/all.css";
import { createVuetify } from "vuetify";
import {
  VAlert,
  VApp,
  VAppBar,
  VAppBarNavIcon,
  VAutocomplete,
  VAvatar,
  VBtn,
  VCard,
  VCardActions,
  VCardText,
  VCardTitle,
  VCheckbox,
  VChip,
  VCol,
  VCombobox,
  VContainer,
  VDialog,
  VDivider,
  VExpansionPanel,
  VExpansionPanelText,
  VExpansionPanels,
  VFileInput,
  VForm,
  VList,
  VListItem,
  VListItemSubtitle,
  VListItemTitle,
  VMain,
  VNavigationDrawer,
  VProgressLinear,
  VRadio,
  VRadioGroup,
  VRow,
  VSelect,
  VSpacer,
  VSwitch,
  VTab,
  VTable,
  VTabs,
  VTextField,
  VTextarea,
  VWindow,
  VWindowItem,
} from "vuetify/components";
import { Ripple } from "vuetify/directives";
import { aliases, fa } from "vuetify/iconsets/fa";
export function makeVuetify() {
  return createVuetify({
    components: {
      VAlert,
      VApp,
      VAppBar,
      VAppBarNavIcon,
      VAutocomplete,
      VAvatar,
      VBtn,
      VCard,
      VCardActions,
      VCardText,
      VCardTitle,
      VCheckbox,
      VChip,
      VCol,
      VCombobox,
      VContainer,
      VDialog,
      VDivider,
      VExpansionPanel,
      VExpansionPanelText,
      VExpansionPanels,
      VFileInput,
      VForm,
      VList,
      VListItem,
      VListItemSubtitle,
      VListItemTitle,
      VMain,
      VNavigationDrawer,
      VProgressLinear,
      VRadio,
      VRadioGroup,
      VRow,
      VSelect,
      VSpacer,
      VSwitch,
      VTab,
      VTable,
      VTabs,
      VTextField,
      VTextarea,
      VWindow,
      VWindowItem,
    },
    directives: { Ripple },
    icons: { defaultSet: "fa", aliases, sets: { fa } },
    theme: {
      defaultTheme: "light",
      themes: {
        light: {
          colors: {
            primary: "#176b70",
            secondary: "#52676a",
            background: "#f5f7f7",
            surface: "#ffffff",
            error: "#b3261e",
          },
        },
        dark: {
          colors: {
            primary: "#79d5d6",
            background: "#101e23",
            surface: "#192b31",
          },
        },
      },
    },
    defaults: {
      VBtn: { rounded: "lg", variant: "flat" },
      VTextField: { variant: "outlined", density: "compact" },
      VAutocomplete: { variant: "outlined", density: "compact" },
      VCombobox: { variant: "outlined", density: "compact" },
      VSelect: { variant: "outlined", density: "compact" },
      VCard: { rounded: "lg", elevation: 0 },
    },
  });
}
