# Generated by Django 2.0.6 on 2018-06-19 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0003_auto_20180619_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicBinary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=30, unique=True)),
                ('type', models.IntegerField(choices=[(1, 'Else'), (2, 'Antropometrie'), (3, 'Life Style'), (4, 'Genetics')])),
                ('value', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharacteristicContinous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=30, unique=True)),
                ('type', models.IntegerField(choices=[(1, 'Else'), (2, 'Antropometrie'), (3, 'Life Style'), (4, 'Genetics')])),
                ('value', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharacteristicRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=30, unique=True)),
                ('type', models.IntegerField(choices=[(1, 'Else'), (2, 'Antropometrie'), (3, 'Life Style'), (4, 'Genetics')])),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelativeAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=30, unique=True)),
                ('specie', models.IntegerField(choices=[(1, 'Else'), (2, 'Homo Sapiens')])),
                ('characteristics_binary', models.ManyToManyField(to='subjects.CharacteristicBinary')),
                ('characteristics_continous', models.ManyToManyField(to='subjects.CharacteristicContinous')),
                ('characteristics_range', models.ManyToManyField(to='subjects.CharacteristicRange')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=30, unique=True)),
                ('number', models.IntegerField()),
                ('Intervention', models.ForeignKey(on_delete=True, to='studies.Intervention')),
                ('subjects', models.ManyToManyField(through='subjects.RelativeAmount', to='subjects.Subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='tags',
            field=models.ManyToManyField(to='subjects.SubjectTag'),
        ),
        migrations.AddField(
            model_name='relativeamount',
            name='subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='relativeamount',
            name='subjects_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.SubjectGroup'),
        ),
    ]
